version: 1.7.0-post{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2013
configuration: Release
environment:
  matrix:
  - platform: x64
  - platform: win32
install:
- ps: "& .\\win32\\install-openssl.ps1"
- ps: "& .\\win32\\install-coapp.ps1"
cache:
- c:\OpenSSL-Win32 -> win32\install-openssl.ps1
- c:\OpenSSL-Win64 -> win32\install-openssl.ps1
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore win32/librdkafka.sln
build:
  project: win32/librdkafka.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
after_build:
- cmd: mkdir "packaging/nuget/dl-6f/p-librdkafka__bld-appveyor__plat-windows__arch-%platform%__bldtype-%configuration%__tag-6f__sha-%APPVEYOR_REPO_COMMIT%"
test_script:
- cmd: cd tests && ..\win32\outdir\v120\%PLATFORM%\%CONFIGURATION%\tests.exe -l -Q -p1 && cd ..
artifacts:
- path: '*.nupkg'
  name: Packages
deploy_script:
- ps: >-

    $dir = 'p-librdkafka__bld-appveyor__plat-windows__arch-{0}__bldtype-{1}__tag-6f__sha-{2}' -f $env:PLATFORM,$env:CONFIGURATION,$env:APPVEYOR_REPO_COMMIT

    Write-Host "$dir"

    $autopkgFile = "win32/librdkafka.autopkg"

    cat ($autopkgFile + ".template") | % { $_ -replace "@version", $env:appveyor_build_version } > $autopkgFile

    Write-NuGetPackage $autopkgFile

    Get-ChildItem .\*.nupkg | Copy-Item -Destination ".\packaging\nuget\dl-6f\$dir" -Force -PassThru

    Set-Location -Path .\packaging\nuget -PassThru

    Get-ChildItem "dl-6f\$dir\"

    7z a "$dir.zip" ".\dl-6f\$dir\*"

    Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
